// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const cleanEnv = (value: string | undefined) =>
  String(value || '')
    .replace(/\\n/g, '')
    .trim();

const SUPABASE_URL = cleanEnv(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_KEY =
  cleanEnv(import.meta.env.VITE_SUPABASE_ANON_KEY) ||
  cleanEnv(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

const supabaseConfigError =
  SUPABASE_URL && SUPABASE_KEY
    ? null
    : 'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.';

const buildDisabledQuery = () => {
  const result = {
    data: null,
    error: supabaseConfigError ? new Error(supabaseConfigError) : null,
  };

  const query: Record<string, any> = {
    select: () => query,
    insert: () => query,
    update: () => query,
    delete: () => query,
    upsert: () => query,
    eq: () => query,
    order: () => query,
    single: () => query,
    maybeSingle: () => query,
    limit: () => query,
    range: () => query,
    neq: () => query,
    ilike: () => query,
    then: (onFulfilled?: (value: typeof result) => unknown, onRejected?: (reason: unknown) => unknown) =>
      Promise.resolve(result).then(onFulfilled, onRejected),
    catch: (onRejected?: (reason: unknown) => unknown) => Promise.resolve(result).catch(onRejected),
    finally: (onFinally?: () => void) => Promise.resolve(result).finally(onFinally),
  };

  return query;
};

const createDisabledClient = () => {
  const authResult = { data: { user: null, session: null }, error: null };
  const subscription = { unsubscribe: () => undefined };
  const channel = {
    on: () => channel,
    subscribe: () => channel,
    unsubscribe: () => undefined,
  };

  return {
    auth: {
      getUser: async () => authResult,
      getSession: async () => authResult,
      signOut: async () => ({ error: null }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: new Error(supabaseConfigError || 'Supabase is not configured.') }),
      signUp: async () => ({ data: { user: null, session: null }, error: new Error(supabaseConfigError || 'Supabase is not configured.') }),
      onAuthStateChange: () => ({ data: { subscription } }),
    },
    from: () => buildDisabledQuery(),
    channel: () => channel,
    removeChannel: () => undefined,
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const isSupabaseConfigured = !supabaseConfigError;

if (supabaseConfigError) {
  console.warn(`[supabase] ${supabaseConfigError}`);
}

export const supabase = (isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
      realtime: {
        enabled: false,
      },
    })
  : createDisabledClient()) as any;